export const MOCK_CUSTOMERS = [
  {
    id: "CUST-001",
    name: "Acme Logistics BV",
    enterprise_number: "BE 0459.832.901",
    customer_code: "SDW-45983",
    industry: "Logistiek, Opslag & Distributie",
    joint_committee: "PC 200 - Aanvullend Paritair Comité voor Bedienden",
    joint_committee_code: "200.00",
    primary_contact: "Marc Vanhove (HR Director)",
    contact_email: "hr@acmelogistics.be",
    contact_phone: "+32 3 205 11 00",
    sdworx_account_manager: "Sarah Vermeulen",
    sdworx_team: "Antwerpen Enterprise - Team 4",
    employee_count: 142,
    location: "Antwerpen (Haven)",
    payroll_frequency: "Maandelijks (25e)",
    active_dossier_status: "Actief • Verwerking Q1",
  },
  {
    id: "CUST-002",
    name: "BioHealth Solutions NV",
    enterprise_number: "BE 0812.445.671",
    customer_code: "SDW-81244",
    industry: "Farmacie & Biotechnologie",
    joint_committee: "PC 207 - Scheikundige Nijverheid",
    joint_committee_code: "207.00",
    primary_contact: "Karin De Meyer (Payroll Lead)",
    contact_email: "k.demeyer@biohealth.be",
    contact_phone: "+32 9 321 44 20",
    sdworx_account_manager: "Emma Wouters",
    sdworx_team: "Gent Corporate & Science",
    employee_count: 320,
    location: "Gent (Zwijnaarde)",
    payroll_frequency: "Maandelijks (28e)",
    active_dossier_status: "Actief • Volcontinue ploegen",
  },
  {
    id: "CUST-003",
    name: "Nexus Digital CommV",
    enterprise_number: "BE 0799.312.118",
    customer_code: "SDW-79931",
    industry: "Software Engineering & Cloud",
    joint_committee: "PC 200 - Bedienden",
    joint_committee_code: "200.00",
    primary_contact: "Pieter Claes (CEO)",
    contact_email: "p.claes@nexusdigital.io",
    contact_phone: "+32 2 400 89 50",
    sdworx_account_manager: "Tom De Smet",
    sdworx_team: "Brussel SME Tech",
    employee_count: 28,
    location: "Brussel (Centrum)",
    payroll_frequency: "Maandelijks (27e)",
    active_dossier_status: "Actief • Cafetariaplan 2026",
  },
  {
    id: "CUST-004",
    name: "Vanderstraeten Bouwgroep NV",
    enterprise_number: "BE 0418.992.341",
    customer_code: "SDW-41899",
    industry: "Algemene Bouw & Infrastructuur",
    joint_committee: "PC 124 - Bouwbedrijf",
    joint_committee_code: "124.00",
    primary_contact: "Luc Vanderstraeten (Bestuurder)",
    contact_email: "personeel@vanderstraeten.be",
    contact_phone: "+32 11 28 30 00",
    sdworx_account_manager: "Tom De Smet",
    sdworx_team: "Hasselt Construction Hub",
    employee_count: 85,
    location: "Hasselt",
    payroll_frequency: "Maandelijks (arbeiders + bedienden)",
    active_dossier_status: "Actief • Weerverlet & Rustdagen",
  },
  {
    id: "CUST-005",
    name: "Grand Palace Hotel & Catering BV",
    enterprise_number: "BE 0652.188.904",
    customer_code: "SDW-65218",
    industry: "Horeca, Hospitality & Evenementen",
    joint_committee: "PC 302 - Horecabedrijf",
    joint_committee_code: "302.00",
    primary_contact: "Annelies Maes (HR Coördinator)",
    contact_email: "hr@grandpalace.be",
    contact_phone: "+32 50 44 12 30",
    sdworx_account_manager: "Kevin Peeters",
    sdworx_team: "Kust & Hospitality Desk",
    employee_count: 54,
    location: "Brugge",
    payroll_frequency: "Maandelijks + Flexi-jobs",
    active_dossier_status: "Actief • Seizoenscontracten",
  },
  {
    id: "CUST-006",
    name: "Flanders Food Processing NV",
    enterprise_number: "BE 0433.819.205",
    customer_code: "SDW-43381",
    industry: "Industriële Voedselproductie",
    joint_committee: "PC 118 - Voedingsnijverheid",
    joint_committee_code: "118.00",
    primary_contact: "Dirk Vansteenkiste (Plant HR)",
    contact_email: "d.vansteenkiste@flandersfood.be",
    contact_phone: "+32 51 22 88 00",
    sdworx_account_manager: "Sarah Vermeulen",
    sdworx_team: "West-Vlaanderen Industry",
    employee_count: 210,
    location: "Roeselare",
    payroll_frequency: "Tweewekelijks / Maandelijks",
    active_dossier_status: "Actief • Nacht- en ploegenpremies",
  },
  {
    id: "CUST-007",
    name: "Metaalconstructies De Smet & Zonen BV",
    enterprise_number: "BE 0429.112.873",
    customer_code: "SDW-42911",
    industry: "Metaalverwerking & Precisiebouw",
    joint_committee: "PC 111 - Metaalbewerkers",
    joint_committee_code: "111.01",
    primary_contact: "Bart De Smet (Afgevaardigd Bestuurder)",
    contact_email: "administratie@desmetmetaal.be",
    contact_phone: "+32 15 34 10 90",
    sdworx_account_manager: "Emma Wouters",
    sdworx_team: "Mechelen Manufacturing",
    employee_count: 62,
    location: "Mechelen",
    payroll_frequency: "Maandelijks",
    active_dossier_status: "Actief • Barema-indexering 2026",
  },
  {
    id: "CUST-008",
    name: "Zorgcampus Sint-Elisabeth VZW",
    enterprise_number: "BE 0214.991.034",
    customer_code: "SDW-21499",
    industry: "Gezondheidszorg & Woonzorgcentra",
    joint_committee: "PC 330 - Gezondheidsinrichtingen",
    joint_committee_code: "330.01",
    primary_contact: "Hilde Goossens (Directeur Personeel)",
    contact_email: "personeelsdienst@sintelizabeth.be",
    contact_phone: "+32 16 38 90 00",
    sdworx_account_manager: "Sarah Vermeulen",
    sdworx_team: "Non-Profit & Healthcare Desk",
    employee_count: 450,
    location: "Leuven",
    payroll_frequency: "Maandelijks (IFIC Barema's)",
    active_dossier_status: "Actief • IFIC Functieclassificatie",
  },
];

export const MOCK_DOCUMENTS = [
  // CUST-001: Acme Logistics BV
  {
    id: "DOC-001",
    customer_id: "CUST-001",
    title: "Getekend Addendum Arbeidsovereenkomst & Thuiswerkbeleid 2024",
    source_type: "SignedContract",
    source_label: "Getekend Contract / Addendum",
    date: "2024-05-12",
    author: "Marc Vanhove & Directie",
    author_role: "Klant HR Directie & SD Worx Legal",
    summary: "Officieel medeondertekend addendum betreffende het voltijds arbeidsregime van 38 uur per week, telewerkmodaliteiten (max. 2 dagen) en representatievergoeding.",
    raw_content: "Overeenkomst gesloten tussen Acme Logistics BV en werknemersvertegenwoordiging. Artikel 3: Het wekelijks werkregime voor alle bedienden onder PC 200 is vastgesteld op exact 38u/week verdeeld over 5 werkdagen. Telewerk is toegestaan voor maximaal 2 dagen per week mits goedkeuring leidinggevende. Referentie medewerker dossier RRN 85.04.12-***.**, bankrekening BE68 **** **** 7034. Bruto basiswedde directieassistentie € [VERTROUWELIJK_SALARIS].",
    unmasked_raw_content: "Overeenkomst gesloten tussen Acme Logistics BV en werknemersvertegenwoordiging. Artikel 3: Het wekelijks werkregime voor alle bedienden onder PC 200 is vastgesteld op exact 38u/week verdeeld over 5 werkdagen. Telewerk is toegestaan voor maximaal 2 dagen per week mits goedkeuring leidinggevende. Referentie medewerker dossier RRN 85.04.12-123.45, bankrekening BE68 5390 0754 7034. Bruto basiswedde directieassistentie € 3.850,00 bruto per maand.",
    key_facts: [
      { field: "werkregime", label: "Wekelijks Werkregime", value: "38u/week", is_conflicting: false },
      { field: "thuiswerk", label: "Structureel Thuiswerk", value: "2 dagen/week", is_conflicting: false },
      { field: "paritair_comite", label: "Paritair Comité", value: "PC 200", is_conflicting: false },
    ],
    tags: ["Contract", "Arbeidsduur", "PC 200", "Thuiswerk"],
    trust: {
      overall_score: 95.0,
      source_score: 100.0,
      recency_score: 88.0,
      consensus_score: 92.0,
      feedback_score: 100.0,
      is_authoritative: true,
      conflict_flag: false,
    },
    feedback: { verified_count: 7, outdated_count: 0, questionable_count: 0 },
  },
  {
    id: "DOC-002",
    customer_id: "CUST-001",
    title: "SD Worx Sectorale Barema & Arbeidsduur Richtlijn PC 200",
    source_type: "OfficialTemplate",
    source_label: "Officiële SD Worx Template",
    date: "2024-01-15",
    author: "SD Worx Kenniscentrum Sociaal Recht",
    author_role: "SD Worx Legal Knowledge Center",
    summary: "Officiële sectorale richtlijn SD Worx voor bedienden onder PC 200. Bevestigt de wettelijke 38-urenweek en indexeringsregels.",
    raw_content: "SD Worx Kennisdossier PC 200. De standaard arbeidsduur bedraagt 38u/week, tenzij op ondernemingsvlak een kortere arbeidsduur werd ingevoerd met ADV-dagen. Maaltijdcheque werkgeversbijdrage maximaal € 6,91 (totaal € 8,00 per gewerkte dag).",
    unmasked_raw_content: "SD Worx Kennisdossier PC 200. De standaard arbeidsduur bedraagt 38u/week, tenzij op ondernemingsvlak een kortere arbeidsduur werd ingevoerd met ADV-dagen. Maaltijdcheque werkgeversbijdrage maximaal € 6,91 (totaal € 8,00 per gewerkte dag).",
    key_facts: [
      { field: "werkregime", label: "Wekelijks Werkregime", value: "38u/week", is_conflicting: false },
      { field: "maaltijdcheque", label: "Maaltijdcheque Nominaal", value: "€ 8,00/dag", is_conflicting: false },
    ],
    tags: ["SD Worx Template", "Barema", "PC 200"],
    trust: {
      overall_score: 91.0,
      source_score: 90.0,
      recency_score: 86.0,
      consensus_score: 92.0,
      feedback_score: 95.0,
      is_authoritative: true,
      conflict_flag: false,
    },
    feedback: { verified_count: 5, outdated_count: 0, questionable_count: 0 },
  },
  {
    id: "DOC-003",
    customer_id: "CUST-001",
    title: "CRM Notitie - Kwartaaloverleg HR & Expat Detacheringen",
    source_type: "CrmNote",
    source_label: "CRM Notitie",
    date: "2025-03-10",
    author: "Sarah Vermeulen",
    author_role: "Senior Payroll Officer SD Worx",
    summary: "Verslag van kwartaaloverleg met Marc Vanhove. Behandeling van 3 internationale detacheringen naar Nederland en bevestiging van de 38u-regeling.",
    raw_content: "Overleg met Marc Vanhove inzake grensoverschrijdend telewerk. Grenswerkers vallen onder A1-verordening met max 49.9% telewerk in woonland. Normale werktijd blijft 38u/week conform Addendum 2024. Contactpersoon Marc goedgekeurd.",
    unmasked_raw_content: "Overleg met Marc Vanhove inzake grensoverschrijdend telewerk. Grenswerkers vallen onder A1-verordening met max 49.9% telewerk in woonland. Normale werktijd blijft 38u/week conform Addendum 2024. Contactpersoon Marc goedgekeurd.",
    key_facts: [
      { field: "werkregime", label: "Wekelijks Werkregime", value: "38u/week", is_conflicting: false },
      { field: "thuiswerk", label: "Structureel Thuiswerk", value: "2 dagen/week", is_conflicting: false },
    ],
    tags: ["CRM", "Expat", "Internationaal", "Overleg"],
    trust: {
      overall_score: 78.0,
      source_score: 75.0,
      recency_score: 82.0,
      consensus_score: 85.0,
      feedback_score: 80.0,
      is_authoritative: false,
      conflict_flag: false,
    },
    feedback: { verified_count: 3, outdated_count: 0, questionable_count: 0 },
  },
  {
    id: "DOC-004",
    customer_id: "CUST-001",
    title: "ServiceDesk Ticket #421 - Vraag inzake Feestdagcompensatie & Werkduur",
    source_type: "TicketComment",
    source_label: "Ticket Commentaar / E-mail",
    date: "2025-09-04",
    author: "Kevin Peeters",
    author_role: "Junior Payroll Consultant SD Worx",
    summary: "Ticketantwoord waarin Kevin per abuis vermeldt dat Acme Logistics op een 36u-regime werkt n.a.v. een vraag over compensatierust voor feestdagen.",
    raw_content: "Beste Marc, voor de berekening van de feestdagvergoeding zijn we uitgegaan van de 36u/week regeling die van toepassing is op de logistieke site. Gelieve dit te bevestigen voor de loonstrook van september.",
    unmasked_raw_content: "Beste Marc, voor de berekening van de feestdagvergoeding zijn we uitgegaan van de 36u/week regeling die van toepassing is op de logistieke site. Gelieve dit te bevestigen voor de loonstrook van september.",
    key_facts: [
      { field: "werkregime", label: "Wekelijks Werkregime", value: "36u/week", is_conflicting: true },
    ],
    tags: ["Ticket", "Feestdagen", "Arbeidsduur"],
    trust: {
      overall_score: 48.0,
      source_score: 50.0,
      recency_score: 72.0,
      consensus_score: 35.0,
      feedback_score: 50.0,
      is_authoritative: false,
      conflict_flag: true,
    },
    feedback: { verified_count: 0, outdated_count: 4, questionable_count: 3 },
  },
  {
    id: "DOC-005",
    customer_id: "CUST-001",
    title: "Teams Notitie - Vaste Brugdagen & Collectieve Sluiting 2026",
    source_type: "ChatMessage",
    source_label: "Teams Chat / Notitie",
    date: "2026-01-14",
    author: "Tom De Smet",
    author_role: "Payroll Consultant SD Worx",
    summary: "Korte chatnotitie met Marc over collectieve sluitingsdagen tussen Kerst en Nieuwjaar.",
    raw_content: "Marc bevestigt via chat: bedrijf sluit op 24/12 en 31/12 in de namiddag. Brugdag op Hemelvaartsdag goedgekeurd door ondernemingsraad.",
    unmasked_raw_content: "Marc bevestigt via chat: bedrijf sluit op 24/12 en 31/12 in de namiddag. Brugdag op Hemelvaartsdag goedgekeurd door ondernemingsraad.",
    key_facts: [
      { field: "brugdagen", label: "Vaste Brugdagen", value: "Hemelvaart + Kerstavond NM", is_conflicting: false },
    ],
    tags: ["Teams", "Sluiting", "Verlof"],
    trust: {
      overall_score: 38.0,
      source_score: 35.0,
      recency_score: 90.0,
      consensus_score: 70.0,
      feedback_score: 60.0,
      is_authoritative: false,
      conflict_flag: false,
    },
    feedback: { verified_count: 1, outdated_count: 0, questionable_count: 1 },
  },

  // CUST-002: BioHealth Solutions NV
  {
    id: "DOC-006",
    customer_id: "CUST-002",
    title: "Bedrijfs-CAO Volcontinu Ploegenarbeid PC 207 (Geregistreerd 2024)",
    source_type: "SignedContract",
    source_label: "Getekend Contract / Bedrijfs-CAO",
    date: "2024-03-20",
    author: "Karin De Meyer & SD Worx Legal",
    author_role: "Ondernemingsraad & SD Worx Jurist",
    summary: "Neergelegde collectieve arbeidsovereenkomst voor 5-ploegenstelsel in chemische productie. Ploegenpremie vastgesteld op 27.5% voor volcontinu.",
    raw_content: "Bedrijfs-CAO BioHealth Solutions NV. Werkduur gemiddeld 33.6u/week in volcontinu cyclus met 12 compensatiedagen per kalenderjaar. Ploegentoeslag ochtend/middag 12.5%, nacht 27.5%. Paritair Comité 207.",
    unmasked_raw_content: "Bedrijfs-CAO BioHealth Solutions NV. Werkduur gemiddeld 33.6u/week in volcontinu cyclus met 12 compensatiedagen per kalenderjaar. Ploegentoeslag ochtend/middag 12.5%, nacht 27.5%. Paritair Comité 207.",
    key_facts: [
      { field: "ploegenregime", label: "Ploegenregime", value: "33.6u/week (5-ploegen)", is_conflicting: false },
      { field: "nachtpremie", label: "Nachttoeslag", value: "27.5%", is_conflicting: false },
      { field: "paritair_comite", label: "Paritair Comité", value: "PC 207", is_conflicting: false },
    ],
    tags: ["CAO", "Ploegenarbeid", "PC 207", "Toeslagen"],
    trust: {
      overall_score: 96.0,
      source_score: 100.0,
      recency_score: 90.0,
      consensus_score: 95.0,
      feedback_score: 100.0,
      is_authoritative: true,
      conflict_flag: false,
    },
    feedback: { verified_count: 9, outdated_count: 0, questionable_count: 0 },
  },
  {
    id: "DOC-007",
    customer_id: "CUST-002",
    title: "Afsprakennota Wachtdiensten & Oproepbaarheid R&D Laboranten",
    source_type: "OfficialTemplate",
    source_label: "SD Worx Policy Nota",
    date: "2025-01-10",
    author: "Emma Wouters",
    author_role: "Legal Advisor SD Worx",
    summary: "Fiscale en sociale behandeling van standby-vergoedingen voor laboranten buiten de reguliere diensturen.",
    raw_content: "Vergoeding voor beschikbaarheid thuis: € 2.45 bruto per uur standby. Bij fysieke oproep minimaal 3 uur uitbetaald aan 150% met verplichte rusttijd van 11 opeenvolgende uren conform arbeidswet.",
    unmasked_raw_content: "Vergoeding voor beschikbaarheid thuis: € 2.45 bruto per uur standby. Bij fysieke oproep minimaal 3 uur uitbetaald aan 150% met verplichte rusttijd van 11 opeenvolgende uren conform arbeidswet.",
    key_facts: [
      { field: "standby_vergoeding", label: "Standby Vergoeding", value: "€ 2.45/uur", is_conflicting: false },
      { field: "oproep_minimaal", label: "Minimale Uitbetaling", value: "3 uur aan 150%", is_conflicting: false },
    ],
    tags: ["Wachtdienst", "R&D", "Overuren"],
    trust: {
      overall_score: 89.0,
      source_score: 90.0,
      recency_score: 92.0,
      consensus_score: 85.0,
      feedback_score: 90.0,
      is_authoritative: true,
      conflict_flag: false,
    },
    feedback: { verified_count: 4, outdated_count: 0, questionable_count: 0 },
  },

  // CUST-004: Vanderstraeten Bouwgroep NV
  {
    id: "DOC-008",
    customer_id: "CUST-004",
    title: "Arbeidsreglement PC 124 Bouw — Winter- en Weerverletregeling 2025",
    source_type: "SignedContract",
    source_label: "Getekend Arbeidsreglement",
    date: "2024-11-01",
    author: "Luc Vanderstraeten & Bouwunie",
    author_role: "Werkgever & Sociale Inspectie",
    summary: "Vastlegging van de 40u-week met 12 toekenningsdagen (ADV) in de bouwsector, getrouwheidszegels en weerverletprocedure via Constructiv.",
    raw_content: "PC 124 Bouwreglement. Wekelijks arbeidsregime 40u/week met 12 rustdagen ter compensatie (38u op jaarbasis). Weerverlet wegens vorst/regen wordt aangegeven via elektronische C3.2A en Constructiv toeslag.",
    unmasked_raw_content: "PC 124 Bouwreglement. Wekelijks arbeidsregime 40u/week met 12 rustdagen ter compensatie (38u op jaarbasis). Weerverlet wegens vorst/regen wordt aangegeven via elektronische C3.2A en Constructiv toeslag.",
    key_facts: [
      { field: "werkregime", label: "Wekelijks Werkregime", value: "40u/week (met 12 ADV)", is_conflicting: false },
      { field: "mobiliteit", label: "Mobiliteitsvergoeding", value: "Volgens barema PC 124", is_conflicting: false },
    ],
    tags: ["Bouw", "PC 124", "Weerverlet", "ADV"],
    trust: {
      overall_score: 94.0,
      source_score: 100.0,
      recency_score: 85.0,
      consensus_score: 92.0,
      feedback_score: 98.0,
      is_authoritative: true,
      conflict_flag: false,
    },
    feedback: { verified_count: 6, outdated_count: 0, questionable_count: 0 },
  },

  // CUST-005: Grand Palace Hotel & Catering BV
  {
    id: "DOC-009",
    customer_id: "CUST-005",
    title: "Kaderovereenkomst Flexi-Job & Gelegenheidsarbeid PC 302",
    source_type: "SignedContract",
    source_label: "Getekend Contract / Raamovereenkomst",
    date: "2025-02-14",
    author: "Annelies Maes",
    author_role: "HR Coördinator Grand Palace",
    summary: "Standaard raamcontract voor flexi-jobbers in de horeca inclusief minimum flexiloon, vakantiegeld (7.67%) en Dimona-Fli registraties.",
    raw_content: "Flexi-arbeidsovereenkomst PC 302 Horeca. Uurloon conform sectoraal minimum inclusief 7.67% flexi-vakantiegeld, vrijgesteld van RSZ en bedrijfsvoorheffing mits 4/5e tewerkstelling bij hoofdwerkgever in T-3.",
    unmasked_raw_content: "Flexi-arbeidsovereenkomst PC 302 Horeca. Uurloon conform sectoraal minimum inclusief 7.67% flexi-vakantiegeld, vrijgesteld van RSZ en bedrijfsvoorheffing mits 4/5e tewerkstelling bij hoofdwerkgever in T-3.",
    key_facts: [
      { field: "flexi_regeling", label: "Flexi-job Toeslag", value: "Inclusief 7.67% vakantiegeld", is_conflicting: false },
      { field: "dimona", label: "Dimona Type", value: "FLI (Flexi-job)", is_conflicting: false },
    ],
    tags: ["Horeca", "PC 302", "Flexi-job", "Dimona"],
    trust: {
      overall_score: 92.0,
      source_score: 100.0,
      recency_score: 94.0,
      consensus_score: 88.0,
      feedback_score: 85.0,
      is_authoritative: true,
      conflict_flag: false,
    },
    feedback: { verified_count: 4, outdated_count: 0, questionable_count: 0 },
  },
];

export const MOCK_CONFLICTS = [
  {
    id: "conflict-CUST-001-werkregime",
    customer_id: "CUST-001",
    topic: "Wekelijks Werkregime",
    field: "werkregime",
    consensus_value: "38u/week",
    impact_severity: "MEDIUM",
    explanation: "Verschil aangetroffen tussen getekend Addendum 2024 (38u/week) en ServiceDesk Ticket #421 (36u/week).",
    resolution_action: "Getekend Addendum (95% betrouwbaarheid) is juridisch leidend. 38u/week toepassen bij loonberekening.",
    conflicting_docs: [
      {
        doc_id: "DOC-001",
        doc_title: "Getekend Addendum Arbeidsovereenkomst 2024",
        source_label: "Getekend Contract / Addendum",
        stated_value: "38u/week",
        trust_score: 95.0,
      },
      {
        doc_id: "DOC-002",
        doc_title: "SD Worx Sectorale Barema Richtlijn PC 200",
        source_label: "Officiële SD Worx Template",
        stated_value: "38u/week",
        trust_score: 91.0,
      },
      {
        doc_id: "DOC-004",
        doc_title: "ServiceDesk Ticket #421",
        source_label: "Ticket Commentaar / E-mail",
        stated_value: "36u/week",
        trust_score: 48.0,
      },
    ],
  },
];

export const MOCK_EMPLOYEES = [
  {
    id: "EMP-001",
    name: "Sarah Vermeulen",
    title: "Senior Payroll Officer & Expat Specialist",
    department: "Enterprise Accounts Antwerpen",
    extension: "4102",
    direct_phone: "+32 3 220 41 02",
    avatar_url: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    availability: "Available",
    completed_cases: 48,
    customer_familiarity: {
      "CUST-001": 95,
      "CUST-002": 40,
      "CUST-003": 25,
      "CUST-006": 92,
      "CUST-008": 88,
    },
    domain_expertise: {
      "Internationale Detachering & Expat": 96,
      "CAO 200 & Bediendenstatuut": 94,
      "Werkregime & Arbeidstijd": 92,
      "Tijdsregistratie & Overuren": 70,
      "Cafetariaplan & Flex Income": 85,
      "Voedingsnijverheid PC 118": 90,
      "Zorgsector PC 330 & IFIC": 88,
    },
    recent_activity: "Loonindexering en grensarbeid afgerond voor Acme Logistics.",
  },
  {
    id: "EMP-002",
    name: "Emma Wouters",
    title: "Legal Advisor Sociaal Recht & Paritair Deskundige",
    department: "SD Worx Kenniscentrum Sociaal Recht",
    extension: "4108",
    direct_phone: "+32 9 320 41 08",
    avatar_url: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80",
    availability: "Available",
    completed_cases: 39,
    customer_familiarity: {
      "CUST-001": 72,
      "CUST-002": 88,
      "CUST-003": 50,
      "CUST-007": 85,
    },
    domain_expertise: {
      "Internationale Detachering & Expat": 98,
      "CAO 200 & Bediendenstatuut": 95,
      "Chemie & Petrochemie PC 207": 96,
      "Metaalsector PC 111": 90,
      "Werkregime & Arbeidstijd": 89,
      "Cafetariaplan & Flex Income": 92,
    },
    recent_activity: "A1-attesten en volcontinu ploegenstelsel BioHealth goedgekeurd.",
  },
  {
    id: "EMP-003",
    name: "Tom De Smet",
    title: "Payroll Consultant & Bouwspecialist PC 124",
    department: "Workforce Solutions Hasselt & Brussel",
    extension: "4115",
    direct_phone: "+32 11 30 41 15",
    avatar_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    availability: "Available",
    completed_cases: 31,
    customer_familiarity: {
      "CUST-001": 60,
      "CUST-002": 30,
      "CUST-003": 85,
      "CUST-004": 94,
    },
    domain_expertise: {
      "Bouwbedrijf PC 124": 96,
      "Tijdsregistratie & Overuren": 96,
      "Werkregime & Arbeidstijd": 88,
      "CAO 200 & Bediendenstatuut": 78,
      "Cafetariaplan & Flex Income": 60,
    },
    recent_activity: "Weerverlet en mobiliteitstoeslag verwerkt voor Vanderstraeten Bouw.",
  },
  {
    id: "EMP-004",
    name: "Kevin Peeters",
    title: "Junior Payroll Officer & Horeca Desk PC 302",
    department: "Frontline ServiceDesk & Hospitality",
    extension: "4122",
    direct_phone: "+32 50 40 41 22",
    avatar_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    availability: "Available",
    completed_cases: 18,
    customer_familiarity: {
      "CUST-001": 35,
      "CUST-002": 15,
      "CUST-003": 20,
      "CUST-005": 90,
    },
    domain_expertise: {
      "Horeca PC 302 & Flexi-jobs": 92,
      "Dimona & Studentenaangiften": 88,
      "Werkregime & Arbeidstijd": 60,
      "CAO 200 & Bediendenstatuut": 55,
    },
    recent_activity: "Flexi-job contracten en weekendverwerking Grand Palace afgerond.",
  },
  {
    id: "EMP-005",
    name: "Anouk Vandenberghe",
    title: "Senior Tax & International Mobility Advisor",
    department: "Executive & Expat Center",
    extension: "4130",
    direct_phone: "+32 2 770 41 30",
    avatar_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    availability: "InCall",
    completed_cases: 42,
    customer_familiarity: {
      "CUST-001": 80,
      "CUST-002": 75,
      "CUST-003": 60,
      "CUST-008": 40,
    },
    domain_expertise: {
      "Internationale Detachering & Expat": 99,
      "Fiscale optimalisatie & Bedrijfswagens": 95,
      "Cafetariaplan & Flex Income": 94,
      "CAO 200 & Bediendenstatuut": 85,
    },
    recent_activity: "Salary split en expat tax regime dossiers in behandeling.",
  },
];
