export const MOCK_CUSTOMERS = [
  {
    id: "CUST-001",
    name: "Acme Logistics BV",
    enterprise_number: "BE 0459.832.901",
    industry: "Logistiek & Supply Chain",
    joint_committee: "PC 200 - Aanvullend Paritair Comité voor Bedienden",
    primary_contact: "Marc Vanhove (HR Director)",
    contact_email: "hr@acmelogistics.be",
    employee_count: 142,
    location: "Haven van Antwerpen",
  },
  {
    id: "CUST-002",
    name: "BioHealth Solutions NV",
    enterprise_number: "BE 0812.445.671",
    industry: "Farmacie & Biotechnologie",
    joint_committee: "PC 207 - Scheikundige Nijverheid",
    primary_contact: "Karin De Meyer (Payroll Lead)",
    contact_email: "k.demeyer@biohealth.be",
    employee_count: 320,
    location: "Gent (Zwijnaarde)",
  },
  {
    id: "CUST-003",
    name: "Nexus Digital CommV",
    enterprise_number: "BE 0799.312.118",
    industry: "IT & Software Development",
    joint_committee: "PC 200 - Bedienden",
    primary_contact: "Pieter Claes (CEO)",
    contact_email: "p.claes@nexusdigital.io",
    employee_count: 28,
    location: "Brussel (Centrum)",
  },
];

export const MOCK_DOCUMENTS = [
  {
    id: "DOC-001",
    customer_id: "CUST-001",
    title: "Getekend Addendum Arbeidsovereenkomst & Thuiswerkbeleid 2024",
    source_type: "SignedContract",
    source_label: "Getekend Contract / Addendum",
    date: "2024-05-12",
    author: "Marc Vanhove & Directie",
    author_role: "Klant HR Directie & SD Worx Legal",
    summary: "Officieel medeondertekend addendum betreffende het voltijds arbeidsregime van 38 uur per week, telewerkmodaliteiten (max. 2 dagen) en representatievergoeding.",
    raw_content: "Overeenkomst gesloten tussen Acme Logistics BV en werknemersvertegenwoordiging. Artikel 3: Het wekelijks werkregime voor alle bedienden onder PC 200 is vastgesteld op exact 38u/week verdeeld over 5 werkdagen. Telewerk is toegestaan voor maximaal 2 dagen per week mits goedkeuring leidinggevende. Referentie medewerker dossier RRN 85.04.12-***.**, bankrekening BE68 **** **** 7034. Bruto basiswedde directieassistentie € [VERTROUWELIJK_SALARIS].",
    unmasked_raw_content: "Overeenkomst gesloten tussen Acme Logistics BV en werknemersvertegenwoordiging. Artikel 3: Het wekelijks werkregime voor alle bedienden onder PC 200 is vastgesteld op exact 38u/week verdeeld over 5 werkdagen. Telewerk is toegestaan voor maximaal 2 dagen per week mits goedkeuring leidinggevende. Referentie medewerker dossier RRN 85.04.12-123.45, bankrekening BE68 5390 0754 7034. Bruto basiswedde directieassistentie € 3.850,00 bruto per maand.",
    key_facts: [
      { field: "werkregime", label: "Wekelijks Werkregime", value: "38u/week", is_conflicting: false },
      { field: "thuiswerk", label: "Structureel Thuiswerk", value: "2 dagen/week", is_conflicting: false },
      { field: "paritair_comite", label: "Paritair Comité", value: "PC 200", is_conflicting: false },
    ],
    tags: ["Contract", "Arbeidsduur", "PC 200", "Thuiswerk"],
    trust: {
      overall_score: 95.0,
      source_score: 100.0,
      recency_score: 88.0,
      consensus_score: 92.0,
      feedback_score: 100.0,
      is_authoritative: true,
      conflict_flag: false,
    },
    feedback: { verified_count: 7, outdated_count: 0, questionable_count: 0 },
  },
  {
    id: "DOC-002",
    customer_id: "CUST-001",
    title: "SD Worx Barema & Arbeidsduur Template PC 200 (Editie 2024)",
    source_type: "OfficialTemplate",
    source_label: "Officiële SD Worx Template",
    date: "2024-01-15",
    author: "SD Worx Kenniscentrum Sociaal Recht",
    author_role: "SD Worx Legal Knowledge Center",
    summary: "Officiële sectorale richtlijn SD Worx voor bedienden onder PC 200. Bevestigt de wettelijke 38-urenweek en de indexeringsregels.",
    raw_content: "SD Worx Kennisdossier PC 200. De standaard arbeidsduur bedraagt 38u/week, tenzij op ondernemingsvlak een kortere arbeidsduur werd ingevoerd met ADV-dagen. Maaltijdcheque werkgeversbijdrage maximaal € 6,91 (totaal € 8,00 per gewerkte dag).",
    unmasked_raw_content: "SD Worx Kennisdossier PC 200. De standaard arbeidsduur bedraagt 38u/week, tenzij op ondernemingsvlak een kortere arbeidsduur werd ingevoerd met ADV-dagen. Maaltijdcheque werkgeversbijdrage maximaal € 6,91 (totaal € 8,00 per gewerkte dag).",
    key_facts: [
      { field: "werkregime", label: "Wekelijks Werkregime", value: "38u/week", is_conflicting: false },
      { field: "maaltijdcheque", label: "Maaltijdcheque Nominaal", value: "€ 8,00/dag", is_conflicting: false },
    ],
    tags: ["SD Worx Template", "Barema", "PC 200"],
    trust: {
      overall_score: 91.0,
      source_score: 90.0,
      recency_score: 86.0,
      consensus_score: 92.0,
      feedback_score: 95.0,
      is_authoritative: true,
      conflict_flag: false,
    },
    feedback: { verified_count: 5, outdated_count: 0, questionable_count: 0 },
  },
  {
    id: "DOC-003",
    customer_id: "CUST-001",
    title: "CRM Notitie - Kwartaaloverleg HR & Expat Afspraken",
    source_type: "CrmNote",
    source_label: "CRM Notitie",
    date: "2025-03-10",
    author: "Sarah Vermeulen",
    author_role: "Senior Payroll Officer SD Worx",
    summary: "Verslag van kwartaaloverleg met Marc Vanhove. Behandeling van 3 internationale detacheringen naar Nederland en bevestiging van de 38u-regeling.",
    raw_content: "Overleg met Marc Vanhove inzake grensoverschrijdend telewerk. Grenswerkers vallen onder A1-verordening met max 49.9% telewerk in woonland. Normale werktijd blijft 38u/week conform Addendum 2024. Contactpersoon Marc goedgekeurd.",
    unmasked_raw_content: "Overleg met Marc Vanhove inzake grensoverschrijdend telewerk. Grenswerkers vallen onder A1-verordening met max 49.9% telewerk in woonland. Normale werktijd blijft 38u/week conform Addendum 2024. Contactpersoon Marc goedgekeurd.",
    key_facts: [
      { field: "werkregime", label: "Wekelijks Werkregime", value: "38u/week", is_conflicting: false },
      { field: "thuiswerk", label: "Structureel Thuiswerk", value: "2 dagen/week", is_conflicting: false },
    ],
    tags: ["CRM", "Expat", "Internationaal", "Overleg"],
    trust: {
      overall_score: 78.0,
      source_score: 75.0,
      recency_score: 82.0,
      consensus_score: 85.0,
      feedback_score: 80.0,
      is_authoritative: false,
      conflict_flag: false,
    },
    feedback: { verified_count: 3, outdated_count: 0, questionable_count: 0 },
  },
  {
    id: "DOC-004",
    customer_id: "CUST-001",
    title: "ServiceDesk Ticket #421 - Vraag inzake Arbeidsduur & Feestdagen",
    source_type: "TicketComment",
    source_label: "Ticket Commentaar / E-mail",
    date: "2025-09-04",
    author: "Kevin Peeters",
    author_role: "Junior HR Consultant SD Worx",
    summary: "Ticketantwoord waarin Kevin per abuis vermeldt dat Acme Logistics op een 36u-regime werkt n.a.v. een vraag over compensatierust.",
    raw_content: "Beste Marc, voor de berekening van de feestdagvergoeding zijn we uitgegaan van de 36u/week regeling die van toepassing is op de logistieke site. Gelieve dit te bevestigen voor de loonstrook van september.",
    unmasked_raw_content: "Beste Marc, voor de berekening van de feestdagvergoeding zijn we uitgegaan van de 36u/week regeling die van toepassing is op de logistieke site. Gelieve dit te bevestigen voor de loonstrook van september.",
    key_facts: [
      { field: "werkregime", label: "Wekelijks Werkregime", value: "36u/week", is_conflicting: true },
    ],
    tags: ["Ticket", "Feestdagen", "Arbeidsduur"],
    trust: {
      overall_score: 48.0,
      source_score: 50.0,
      recency_score: 72.0,
      consensus_score: 35.0,
      feedback_score: 50.0,
      is_authoritative: false,
      conflict_flag: true,
    },
    feedback: { verified_count: 0, outdated_count: 4, questionable_count: 3 },
  },
  {
    id: "DOC-005",
    customer_id: "CUST-001",
    title: "Teams Notitie - Vaste Brugdagen & Collectieve Sluiting",
    source_type: "ChatMessage",
    source_label: "Teams Chat / Notitie",
    date: "2026-01-14",
    author: "Tom De Smet",
    author_role: "Payroll Consultant SD Worx",
    summary: "Korte chatnotitie met Marc over collectieve sluitingsdagen tussen Kerst en Nieuwjaar.",
    raw_content: "Marc bevestigt via chat: bedrijf sluit op 24/12 en 31/12 in de namiddag. Brugdag op Hemelvaartsdag goedgekeurd door ondernemingsraad.",
    unmasked_raw_content: "Marc bevestigt via chat: bedrijf sluit op 24/12 en 31/12 in de namiddag. Brugdag op Hemelvaartsdag goedgekeurd door ondernemingsraad.",
    key_facts: [
      { field: "brugdagen", label: "Vaste Brugdagen", value: "Hemelvaart + Kerstavond NM", is_conflicting: false },
    ],
    tags: ["Teams", "Sluiting", "Verlof"],
    trust: {
      overall_score: 38.0,
      source_score: 35.0,
      recency_score: 90.0,
      consensus_score: 70.0,
      feedback_score: 60.0,
      is_authoritative: false,
      conflict_flag: false,
    },
    feedback: { verified_count: 1, outdated_count: 0, questionable_count: 1 },
  },
];

export const MOCK_CONFLICTS = [
  {
    id: "conflict-CUST-001-werkregime",
    customer_id: "CUST-001",
    topic: "Wekelijks Werkregime",
    field: "werkregime",
    consensus_value: "38u/week",
    impact_severity: "CRITICAL",
    explanation: "Tegenstrijdigheid ontdekt: Er zijn 2 afwijkende arbeidsregimes aangetroffen in recente klantdossiers (38u/week vs. 36u/week).",
    resolution_action: "Volg '38u/week' conform Getekend Addendum Arbeidsovereenkomst 2024 (95% Trust Score). Het antwoord in Ticket #421 berust op een administratieve vergissing.",
    conflicting_docs: [
      {
        doc_id: "DOC-001",
        doc_title: "Getekend Addendum Arbeidsovereenkomst 2024",
        source_label: "Getekend Contract / Addendum",
        stated_value: "38u/week",
        trust_score: 95.0,
      },
      {
        doc_id: "DOC-002",
        doc_title: "SD Worx Sectorale Barematemplate PC 200",
        source_label: "Officiële SD Worx Template",
        stated_value: "38u/week",
        trust_score: 91.0,
      },
      {
        doc_id: "DOC-004",
        doc_title: "ServiceDesk Ticket #421",
        source_label: "Ticket Commentaar / E-mail",
        stated_value: "36u/week",
        trust_score: 48.0,
      },
    ],
  },
];

export const MOCK_EMPLOYEES = [
  {
    id: "EMP-001",
    name: "Sarah Vermeulen",
    title: "Senior Payroll Officer & Expat Lead",
    department: "SME & Enterprise Large Accounts",
    avatar_url: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    availability: "Available",
    completed_cases: 48,
    customer_familiarity: { "CUST-001": 95, "CUST-002": 40, "CUST-003": 25 },
    domain_expertise: {
      "Internationale Detachering & Expat": 96,
      "CAO 200 & Bediendenstatuut": 94,
      "Werkregime & Arbeidstijd": 92,
      "Tijdsregistratie & Overuren": 70,
      "Cafetariaplan & Flex Income": 85,
    },
    recent_activity: "Loonindexering januari en telewerkaanpassing afgerond voor Acme Logistics.",
  },
  {
    id: "EMP-002",
    name: "Emma Wouters",
    title: "Legal Advisor Sociaal Recht",
    department: "SD Worx Legal Knowledge Center",
    avatar_url: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80",
    availability: "Available",
    completed_cases: 39,
    customer_familiarity: { "CUST-001": 72, "CUST-002": 88, "CUST-003": 50 },
    domain_expertise: {
      "Internationale Detachering & Expat": 98,
      "CAO 200 & Bediendenstatuut": 95,
      "Werkregime & Arbeidstijd": 89,
      "Tijdsregistratie & Overuren": 65,
      "Cafetariaplan & Flex Income": 92,
    },
    recent_activity: "A1-aanvragen en grensarbeid dossiers goedgekeurd.",
  },
  {
    id: "EMP-003",
    name: "Tom De Smet",
    title: "Consultant Tijdsregistratie & Planning",
    department: "Workforce Management Solutions",
    avatar_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    availability: "InCall",
    completed_cases: 31,
    customer_familiarity: { "CUST-001": 60, "CUST-002": 30, "CUST-003": 85 },
    domain_expertise: {
      "Tijdsregistratie & Overuren": 96,
      "Werkregime & Arbeidstijd": 88,
      "CAO 200 & Bediendenstatuut": 78,
      "Internationale Detachering & Expat": 45,
      "Cafetariaplan & Flex Income": 60,
    },
    recent_activity: "In gesprek met Nexus Digital over overurenregistratie.",
  },
  {
    id: "EMP-004",
    name: "Kevin Peeters",
    title: "Junior Payroll & Customer Support",
    department: "ServiceDesk Frontline",
    avatar_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    availability: "Available",
    completed_cases: 14,
    customer_familiarity: { "CUST-001": 35, "CUST-002": 15, "CUST-003": 20 },
    domain_expertise: {
      "Werkregime & Arbeidstijd": 60,
      "CAO 200 & Bediendenstatuut": 55,
      "Tijdsregistratie & Overuren": 65,
      "Internationale Detachering & Expat": 25,
      "Cafetariaplan & Flex Income": 40,
    },
    recent_activity: "Eerste lijns ticket triage afgerond.",
  },
];

export const MOCK_AUDIT_ENTRIES = [
  {
    index: 0,
    timestamp: new Date(Date.now() - 3600000).toISOString(),
    actor: "SYSTEM",
    actor_role: "SecuritySupervisor",
    action: "INITIALIZE_GENESIS",
    resource: "SYSTEM_ROOT",
    details: "Tectonic Cryptographic Audit Ledger geïnitialiseerd conform SD Worx Beveiligingsbeleid.",
    prev_hash: "0000000000000000000000000000000000000000000000000000000000000000",
    hash: "a4f89d312bc89e34e21a007f59d2801e0a298bf09a63e804f58c8942b01243ca",
  },
  {
    index: 1,
    timestamp: new Date(Date.now() - 1800000).toISOString(),
    actor: "Tom De Smet",
    actor_role: "Consultant",
    action: "VIEW_CUSTOMER_DOCUMENTS",
    resource: "CUST-001",
    details: "Documenten geconsulteerd voor klant CUST-001 (Acme Logistics BV). PII gemaskeerd: true, Conflicten: 1",
    prev_hash: "a4f89d312bc89e34e21a007f59d2801e0a298bf09a63e804f58c8942b01243ca",
    hash: "b7289f81d871923ec09138402a7812984ef018274acb90128492ef01827364aa",
  },
  {
    index: 2,
    timestamp: new Date(Date.now() - 600000).toISOString(),
    actor: "ROUTING_ENGINE",
    actor_role: "AlgorithmicRouter",
    action: "CALCULATE_ROUTING_MATCH",
    resource: "CUST-001",
    details: "Beste matches berekend voor domein 'Internationale Detachering & Expat'. Top match: Sarah Vermeulen (94%).",
    prev_hash: "b7289f81d871923ec09138402a7812984ef018274acb90128492ef01827364aa",
    hash: "91ce0a83021876402fbba71625390aef89124a900216781239bc7aef129038ba",
  },
];
